spring:
  application:
    name: api-gateway-eureka

server:
  port: 1101

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
